# Generated by Django 5.1.5 on 2025-03-22 13:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userphoto',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='disliked_photos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userphoto',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_photos', to=settings.AUTH_USER_MODEL),
        ),
    ]
